[general]
live_config_reload = true

[window]
startup_mode = "maximized"
decorations = "full"

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold" }
italic = { family = "0xProto Nerd Font", style = "Italic" }
bold_italic = { family = "0xProto Nerd Font", style = "Bold Italic" }
